Vagrant.configure("2") do |config|

    vmCounts = 1
    vmNamePrefix = "hbase"

    hostnamePrefix = "hbase"

    ipPrefix = "192.168.57"
    ipBegin = 100

    vagrantTip="hbase"

    (1..vmCounts).each do |i|
         config.vm.define "#{vagrantTip}#{i}" do |node|
             node.vm.box = "ubuntu/bionic"
             node.vm.hostname="#{hostnamePrefix}#{i}"
             node.vm.network "private_network", ip: "#{ipPrefix}.#{ipBegin + i}"

             # 完成解压、设置环境、设置SSH等工作
             node.vm.provision "shell", privileged: false, path: "software/jdk/init.sh"
             node.vm.provision "shell", privileged: false, path: "software/hbase/init.sh"
             node.vm.provision "shell", privileged: false, path: "software/ssh/init.sh"
             # node.vm.provision "shell", privileged: false, path: "software/hadoop/init.sh"


             # 设置host文件
             hosts = "0.0.0.0\tlocalhost\n"
             # hosts = ""
             for j in 1..vmCounts
                if j == i then
                    hosts += "0.0.0.0\t#{hostnamePrefix}#{j}\n"
                else
                    hosts += "#{ipPrefix}.#{ipBegin + j}\t#{hostnamePrefix}#{j}\n"
                end
             end
             node.vm.provision "shell", privileged: false, inline: "echo '#{hosts}' | sudo tee /etc/hosts"
             
             # 设置主机与虚拟机的共享目录
             node.vm.synced_folder ".", "/vagrant"
 
             # VirtaulBox相关配置
             node.vm.provider "virtualbox" do |v|
                 v.name = "#{hostnamePrefix}#{i}"
                 v.memory = 1024
                 v.cpus = 1
             end
         end
    end
 end